import { LayoutSetting } from '../../types/layout.ts'

export default {
  title: 'Antdv Pro',
  theme: 'light',
  logo: '/logo.svg',
  collapsed: false,
  drawerVisible: true,
  colorPrimary: '#FA541C',
  layout: 'side',
  contentWidth: 'Fluid',
  fixedHeader: false,
  fixedSider: true,
  splitMenus: false,
  header: true,
  menu: true,
  watermark: true,
  menuHeader: true,
  footer: false,
  colorWeak: false,
  colorGray: false,
  multiTab: true,
  multiTabFixed: true,
  keepAlive: true,
  accordionMode: false,
  leftCollapsed: true,
  compactAlgorithm: false,
  headerHeight: 48,
  copyright: 'Antdv Pro Team 2023',
  animationName: 'none',
} as LayoutSetting
